/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as CompressIndexRouteImport } from './routes/compress.index'
import { Route as ScanResultsRouteImport } from './routes/scan.results'
import { Route as CompressProgressRouteImport } from './routes/compress.progress'
import { Route as AppVaultRouteImport } from './routes/_app.vault'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppHomeRouteImport } from './routes/_app.home'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressIndexRoute = CompressIndexRouteImport.update({
  id: '/compress/',
  path: '/compress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan/results',
  path: '/scan/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressProgressRoute = CompressProgressRouteImport.update({
  id: '/compress/progress',
  path: '/compress/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/permissions': typeof PermissionsRoute
  '/review': typeof ReviewRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/jobs': typeof AppJobsRoute
  '/settings': typeof AppSettingsRoute
  '/vault': typeof AppVaultRoute
  '/compress/progress': typeof CompressProgressRoute
  '/scan/results': typeof ScanResultsRoute
  '/compress/': typeof CompressIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/permissions': typeof PermissionsRoute
  '/review': typeof ReviewRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/jobs': typeof AppJobsRoute
  '/settings': typeof AppSettingsRoute
  '/vault': typeof AppVaultRoute
  '/compress/progress': typeof CompressProgressRoute
  '/scan/results': typeof ScanResultsRoute
  '/compress': typeof CompressIndexRoute
  '/scan': typeof ScanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/complete': typeof CompleteRoute
  '/permissions': typeof PermissionsRoute
  '/review': typeof ReviewRoute
  '/welcome': typeof WelcomeRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vault': typeof AppVaultRoute
  '/compress/progress': typeof CompressProgressRoute
  '/scan/results': typeof ScanResultsRoute
  '/compress/': typeof CompressIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/permissions'
    | '/review'
    | '/welcome'
    | '/home'
    | '/jobs'
    | '/settings'
    | '/vault'
    | '/compress/progress'
    | '/scan/results'
    | '/compress/'
    | '/scan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/permissions'
    | '/review'
    | '/welcome'
    | '/home'
    | '/jobs'
    | '/settings'
    | '/vault'
    | '/compress/progress'
    | '/scan/results'
    | '/compress'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/complete'
    | '/permissions'
    | '/review'
    | '/welcome'
    | '/_app/home'
    | '/_app/jobs'
    | '/_app/settings'
    | '/_app/vault'
    | '/compress/progress'
    | '/scan/results'
    | '/compress/'
    | '/scan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CompleteRoute: typeof CompleteRoute
  PermissionsRoute: typeof PermissionsRoute
  ReviewRoute: typeof ReviewRoute
  WelcomeRoute: typeof WelcomeRoute
  CompressProgressRoute: typeof CompressProgressRoute
  ScanResultsRoute: typeof ScanResultsRoute
  CompressIndexRoute: typeof CompressIndexRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/': {
      id: '/compress/'
      path: '/compress'
      fullPath: '/compress/'
      preLoaderRoute: typeof CompressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/results': {
      id: '/scan/results'
      path: '/scan/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/progress': {
      id: '/compress/progress'
      path: '/compress/progress'
      fullPath: '/compress/progress'
      preLoaderRoute: typeof CompressProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppJobsRoute: typeof AppJobsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVaultRoute: typeof AppVaultRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppJobsRoute: AppJobsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVaultRoute: AppVaultRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CompleteRoute: CompleteRoute,
  PermissionsRoute: PermissionsRoute,
  ReviewRoute: ReviewRoute,
  WelcomeRoute: WelcomeRoute,
  CompressProgressRoute: CompressProgressRoute,
  ScanResultsRoute: ScanResultsRoute,
  CompressIndexRoute: CompressIndexRoute,
  ScanIndexRoute: ScanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
