/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as CompressIndexRouteImport } from './routes/compress.index'
import { Route as SettingsTermsRouteImport } from './routes/settings.terms'
import { Route as SettingsReportBugRouteImport } from './routes/settings.report-bug'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsLicensesRouteImport } from './routes/settings.licenses'
import { Route as SettingsFeedbackRouteImport } from './routes/settings.feedback'
import { Route as SettingsChangelogRouteImport } from './routes/settings.changelog'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as ScanResultsRouteImport } from './routes/scan.results'
import { Route as CompressProgressRouteImport } from './routes/compress.progress'
import { Route as AppVaultRouteImport } from './routes/_app.vault'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppVaultVideosRouteImport } from './routes/_app.vault.videos'
import { Route as AppVaultPhotosRouteImport } from './routes/_app.vault.photos'
import { Route as AppVaultDeletedRouteImport } from './routes/_app.vault.deleted'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressIndexRoute = CompressIndexRouteImport.update({
  id: '/compress/',
  path: '/compress/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTermsRoute = SettingsTermsRouteImport.update({
  id: '/settings/terms',
  path: '/settings/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsReportBugRoute = SettingsReportBugRouteImport.update({
  id: '/settings/report-bug',
  path: '/settings/report-bug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLicensesRoute = SettingsLicensesRouteImport.update({
  id: '/settings/licenses',
  path: '/settings/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFeedbackRoute = SettingsFeedbackRouteImport.update({
  id: '/settings/feedback',
  path: '/settings/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChangelogRoute = SettingsChangelogRouteImport.update({
  id: '/settings/changelog',
  path: '/settings/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan/results',
  path: '/scan/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressProgressRoute = CompressProgressRouteImport.update({
  id: '/compress/progress',
  path: '/compress/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultVideosRoute = AppVaultVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppVaultRoute,
} as any)
const AppVaultPhotosRoute = AppVaultPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppVaultRoute,
} as any)
const AppVaultDeletedRoute = AppVaultDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => AppVaultRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/permissions': typeof PermissionsRoute
  '/review': typeof ReviewRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/jobs': typeof AppJobsRoute
  '/settings': typeof AppSettingsRoute
  '/vault': typeof AppVaultRouteWithChildren
  '/compress/progress': typeof CompressProgressRoute
  '/scan/results': typeof ScanResultsRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/changelog': typeof SettingsChangelogRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/licenses': typeof SettingsLicensesRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/report-bug': typeof SettingsReportBugRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/compress/': typeof CompressIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/vault/deleted': typeof AppVaultDeletedRoute
  '/vault/photos': typeof AppVaultPhotosRoute
  '/vault/videos': typeof AppVaultVideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/permissions': typeof PermissionsRoute
  '/review': typeof ReviewRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/jobs': typeof AppJobsRoute
  '/settings': typeof AppSettingsRoute
  '/vault': typeof AppVaultRouteWithChildren
  '/compress/progress': typeof CompressProgressRoute
  '/scan/results': typeof ScanResultsRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/changelog': typeof SettingsChangelogRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/licenses': typeof SettingsLicensesRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/report-bug': typeof SettingsReportBugRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/compress': typeof CompressIndexRoute
  '/scan': typeof ScanIndexRoute
  '/vault/deleted': typeof AppVaultDeletedRoute
  '/vault/photos': typeof AppVaultPhotosRoute
  '/vault/videos': typeof AppVaultVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/complete': typeof CompleteRoute
  '/permissions': typeof PermissionsRoute
  '/review': typeof ReviewRoute
  '/welcome': typeof WelcomeRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vault': typeof AppVaultRouteWithChildren
  '/compress/progress': typeof CompressProgressRoute
  '/scan/results': typeof ScanResultsRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/changelog': typeof SettingsChangelogRoute
  '/settings/feedback': typeof SettingsFeedbackRoute
  '/settings/licenses': typeof SettingsLicensesRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/report-bug': typeof SettingsReportBugRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/compress/': typeof CompressIndexRoute
  '/scan/': typeof ScanIndexRoute
  '/_app/vault/deleted': typeof AppVaultDeletedRoute
  '/_app/vault/photos': typeof AppVaultPhotosRoute
  '/_app/vault/videos': typeof AppVaultVideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/permissions'
    | '/review'
    | '/welcome'
    | '/home'
    | '/jobs'
    | '/settings'
    | '/vault'
    | '/compress/progress'
    | '/scan/results'
    | '/settings/about'
    | '/settings/changelog'
    | '/settings/feedback'
    | '/settings/licenses'
    | '/settings/privacy'
    | '/settings/report-bug'
    | '/settings/terms'
    | '/compress/'
    | '/scan/'
    | '/vault/deleted'
    | '/vault/photos'
    | '/vault/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/permissions'
    | '/review'
    | '/welcome'
    | '/home'
    | '/jobs'
    | '/settings'
    | '/vault'
    | '/compress/progress'
    | '/scan/results'
    | '/settings/about'
    | '/settings/changelog'
    | '/settings/feedback'
    | '/settings/licenses'
    | '/settings/privacy'
    | '/settings/report-bug'
    | '/settings/terms'
    | '/compress'
    | '/scan'
    | '/vault/deleted'
    | '/vault/photos'
    | '/vault/videos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/complete'
    | '/permissions'
    | '/review'
    | '/welcome'
    | '/_app/home'
    | '/_app/jobs'
    | '/_app/settings'
    | '/_app/vault'
    | '/compress/progress'
    | '/scan/results'
    | '/settings/about'
    | '/settings/changelog'
    | '/settings/feedback'
    | '/settings/licenses'
    | '/settings/privacy'
    | '/settings/report-bug'
    | '/settings/terms'
    | '/compress/'
    | '/scan/'
    | '/_app/vault/deleted'
    | '/_app/vault/photos'
    | '/_app/vault/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CompleteRoute: typeof CompleteRoute
  PermissionsRoute: typeof PermissionsRoute
  ReviewRoute: typeof ReviewRoute
  WelcomeRoute: typeof WelcomeRoute
  CompressProgressRoute: typeof CompressProgressRoute
  ScanResultsRoute: typeof ScanResultsRoute
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsChangelogRoute: typeof SettingsChangelogRoute
  SettingsFeedbackRoute: typeof SettingsFeedbackRoute
  SettingsLicensesRoute: typeof SettingsLicensesRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsReportBugRoute: typeof SettingsReportBugRoute
  SettingsTermsRoute: typeof SettingsTermsRoute
  CompressIndexRoute: typeof CompressIndexRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/': {
      id: '/compress/'
      path: '/compress'
      fullPath: '/compress/'
      preLoaderRoute: typeof CompressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terms': {
      id: '/settings/terms'
      path: '/settings/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof SettingsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/report-bug': {
      id: '/settings/report-bug'
      path: '/settings/report-bug'
      fullPath: '/settings/report-bug'
      preLoaderRoute: typeof SettingsReportBugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/licenses': {
      id: '/settings/licenses'
      path: '/settings/licenses'
      fullPath: '/settings/licenses'
      preLoaderRoute: typeof SettingsLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/feedback': {
      id: '/settings/feedback'
      path: '/settings/feedback'
      fullPath: '/settings/feedback'
      preLoaderRoute: typeof SettingsFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/changelog': {
      id: '/settings/changelog'
      path: '/settings/changelog'
      fullPath: '/settings/changelog'
      preLoaderRoute: typeof SettingsChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/results': {
      id: '/scan/results'
      path: '/scan/results'
      fullPath: '/scan/results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress/progress': {
      id: '/compress/progress'
      path: '/compress/progress'
      fullPath: '/compress/progress'
      preLoaderRoute: typeof CompressProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault/videos': {
      id: '/_app/vault/videos'
      path: '/videos'
      fullPath: '/vault/videos'
      preLoaderRoute: typeof AppVaultVideosRouteImport
      parentRoute: typeof AppVaultRoute
    }
    '/_app/vault/photos': {
      id: '/_app/vault/photos'
      path: '/photos'
      fullPath: '/vault/photos'
      preLoaderRoute: typeof AppVaultPhotosRouteImport
      parentRoute: typeof AppVaultRoute
    }
    '/_app/vault/deleted': {
      id: '/_app/vault/deleted'
      path: '/deleted'
      fullPath: '/vault/deleted'
      preLoaderRoute: typeof AppVaultDeletedRouteImport
      parentRoute: typeof AppVaultRoute
    }
  }
}

interface AppVaultRouteChildren {
  AppVaultDeletedRoute: typeof AppVaultDeletedRoute
  AppVaultPhotosRoute: typeof AppVaultPhotosRoute
  AppVaultVideosRoute: typeof AppVaultVideosRoute
}

const AppVaultRouteChildren: AppVaultRouteChildren = {
  AppVaultDeletedRoute: AppVaultDeletedRoute,
  AppVaultPhotosRoute: AppVaultPhotosRoute,
  AppVaultVideosRoute: AppVaultVideosRoute,
}

const AppVaultRouteWithChildren = AppVaultRoute._addFileChildren(
  AppVaultRouteChildren,
)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppJobsRoute: typeof AppJobsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVaultRoute: typeof AppVaultRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppJobsRoute: AppJobsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVaultRoute: AppVaultRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CompleteRoute: CompleteRoute,
  PermissionsRoute: PermissionsRoute,
  ReviewRoute: ReviewRoute,
  WelcomeRoute: WelcomeRoute,
  CompressProgressRoute: CompressProgressRoute,
  ScanResultsRoute: ScanResultsRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsChangelogRoute: SettingsChangelogRoute,
  SettingsFeedbackRoute: SettingsFeedbackRoute,
  SettingsLicensesRoute: SettingsLicensesRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsReportBugRoute: SettingsReportBugRoute,
  SettingsTermsRoute: SettingsTermsRoute,
  CompressIndexRoute: CompressIndexRoute,
  ScanIndexRoute: ScanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
